#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

frameworkVersion=net471
netfx=${frameworkVersion#net}

echo "[INFO] Target framework: ${frameworkVersion}"

echo "[INFO] Download nuget and packages"
wget -nc https://nuget.org/nuget.exe;
mozroots --import --sync
mono nuget.exe install src/DocuSign.eSign/packages.config -o packages;

echo "[INFO] Copy DLLs to the 'bin' folder"
mkdir -p bin;
cp packages/Newtonsoft.Json.11.0.2/lib/net471/Newtonsoft.Json.dll bin/Newtonsoft.Json.dll;
cp packages/RestSharpSigned.105.2.3/lib/net471/RestSharp.dll bin/RestSharp.dll;

echo "[INFO] Run 'mcs' to build bin/DocuSign.eSign.dll"
mcs -sdk:${netfx} -r:bin/Newtonsoft.Json.dll,\
bin/RestSharp.dll,\
System.ComponentModel.DataAnnotations.dll,\
System.Runtime.Serialization.dll \
-target:library \
-out:bin/DocuSign.eSign.dll \
-recurse:'src/DocuSign.eSign/*.cs' \
-doc:bin/DocuSign.eSign.xml \
-platform:anycpu

if [ $? -ne 0 ]
then
  echo "[ERROR] Compilation failed with exit code $?"
  exit 1
else
  echo "[INFO] bin/DocuSign.eSign.dll was created successfully"
fi
