/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing AccountRoleSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class AccountRoleSettingsTests
    {
        // TODO uncomment below to declare an instance variable for AccountRoleSettings
        //private AccountRoleSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountRoleSettings
            //instance = new AccountRoleSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountRoleSettings
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountRoleSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountRoleSettings
            //NUnit.Framework.Assert.IsInstanceOf<AccountRoleSettings> (instance, "variable 'instance' is a AccountRoleSettings");
        }

        /// <summary>
        /// Test the property 'AllowAccountManagement'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowAccountManagementTest()
        {
            // TODO unit test for the property 'AllowAccountManagement'
        }
        /// <summary>
        /// Test the property 'AllowAccountManagementMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowAccountManagementMetadataTest()
        {
            // TODO unit test for the property 'AllowAccountManagementMetadata'
        }
        /// <summary>
        /// Test the property 'AllowApiAccess'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiAccessTest()
        {
            // TODO unit test for the property 'AllowApiAccess'
        }
        /// <summary>
        /// Test the property 'AllowApiAccessMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiAccessMetadataTest()
        {
            // TODO unit test for the property 'AllowApiAccessMetadata'
        }
        /// <summary>
        /// Test the property 'AllowApiAccessToAccount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiAccessToAccountTest()
        {
            // TODO unit test for the property 'AllowApiAccessToAccount'
        }
        /// <summary>
        /// Test the property 'AllowApiAccessToAccountMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiAccessToAccountMetadataTest()
        {
            // TODO unit test for the property 'AllowApiAccessToAccountMetadata'
        }
        /// <summary>
        /// Test the property 'AllowApiSendingOnBehalfOfOthers'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiSendingOnBehalfOfOthersTest()
        {
            // TODO unit test for the property 'AllowApiSendingOnBehalfOfOthers'
        }
        /// <summary>
        /// Test the property 'AllowApiSendingOnBehalfOfOthersMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiSendingOnBehalfOfOthersMetadataTest()
        {
            // TODO unit test for the property 'AllowApiSendingOnBehalfOfOthersMetadata'
        }
        /// <summary>
        /// Test the property 'AllowApiSequentialSigning'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiSequentialSigningTest()
        {
            // TODO unit test for the property 'AllowApiSequentialSigning'
        }
        /// <summary>
        /// Test the property 'AllowApiSequentialSigningMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowApiSequentialSigningMetadataTest()
        {
            // TODO unit test for the property 'AllowApiSequentialSigningMetadata'
        }
        /// <summary>
        /// Test the property 'AllowBulkSending'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowBulkSendingTest()
        {
            // TODO unit test for the property 'AllowBulkSending'
        }
        /// <summary>
        /// Test the property 'AllowBulkSendingMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowBulkSendingMetadataTest()
        {
            // TODO unit test for the property 'AllowBulkSendingMetadata'
        }
        /// <summary>
        /// Test the property 'AllowDocuSignDesktopClient'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowDocuSignDesktopClientTest()
        {
            // TODO unit test for the property 'AllowDocuSignDesktopClient'
        }
        /// <summary>
        /// Test the property 'AllowDocuSignDesktopClientMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowDocuSignDesktopClientMetadataTest()
        {
            // TODO unit test for the property 'AllowDocuSignDesktopClientMetadata'
        }
        /// <summary>
        /// Test the property 'AllowedAddressBookAccess'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowedAddressBookAccessTest()
        {
            // TODO unit test for the property 'AllowedAddressBookAccess'
        }
        /// <summary>
        /// Test the property 'AllowedAddressBookAccessMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowedAddressBookAccessMetadataTest()
        {
            // TODO unit test for the property 'AllowedAddressBookAccessMetadata'
        }
        /// <summary>
        /// Test the property 'AllowedTemplateAccess'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowedTemplateAccessTest()
        {
            // TODO unit test for the property 'AllowedTemplateAccess'
        }
        /// <summary>
        /// Test the property 'AllowedTemplateAccessMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowedTemplateAccessMetadataTest()
        {
            // TODO unit test for the property 'AllowedTemplateAccessMetadata'
        }
        /// <summary>
        /// Test the property 'AllowedToBeEnvelopeTransferRecipient'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowedToBeEnvelopeTransferRecipientTest()
        {
            // TODO unit test for the property 'AllowedToBeEnvelopeTransferRecipient'
        }
        /// <summary>
        /// Test the property 'AllowedToBeEnvelopeTransferRecipientMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowedToBeEnvelopeTransferRecipientMetadataTest()
        {
            // TODO unit test for the property 'AllowedToBeEnvelopeTransferRecipientMetadata'
        }
        /// <summary>
        /// Test the property 'AllowEnvelopeSending'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowEnvelopeSendingTest()
        {
            // TODO unit test for the property 'AllowEnvelopeSending'
        }
        /// <summary>
        /// Test the property 'AllowEnvelopeSendingMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowEnvelopeSendingMetadataTest()
        {
            // TODO unit test for the property 'AllowEnvelopeSendingMetadata'
        }
        /// <summary>
        /// Test the property 'AllowSendersToSetRecipientEmailLanguage'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSendersToSetRecipientEmailLanguageTest()
        {
            // TODO unit test for the property 'AllowSendersToSetRecipientEmailLanguage'
        }
        /// <summary>
        /// Test the property 'AllowSendersToSetRecipientEmailLanguageMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSendersToSetRecipientEmailLanguageMetadataTest()
        {
            // TODO unit test for the property 'AllowSendersToSetRecipientEmailLanguageMetadata'
        }
        /// <summary>
        /// Test the property 'AllowSignerAttachments'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSignerAttachmentsTest()
        {
            // TODO unit test for the property 'AllowSignerAttachments'
        }
        /// <summary>
        /// Test the property 'AllowSignerAttachmentsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSignerAttachmentsMetadataTest()
        {
            // TODO unit test for the property 'AllowSignerAttachmentsMetadata'
        }
        /// <summary>
        /// Test the property 'AllowSupplementalDocuments'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSupplementalDocumentsTest()
        {
            // TODO unit test for the property 'AllowSupplementalDocuments'
        }
        /// <summary>
        /// Test the property 'AllowSupplementalDocumentsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSupplementalDocumentsMetadataTest()
        {
            // TODO unit test for the property 'AllowSupplementalDocumentsMetadata'
        }
        /// <summary>
        /// Test the property 'AllowTaggingInSendAndCorrect'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowTaggingInSendAndCorrectTest()
        {
            // TODO unit test for the property 'AllowTaggingInSendAndCorrect'
        }
        /// <summary>
        /// Test the property 'AllowTaggingInSendAndCorrectMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowTaggingInSendAndCorrectMetadataTest()
        {
            // TODO unit test for the property 'AllowTaggingInSendAndCorrectMetadata'
        }
        /// <summary>
        /// Test the property 'AllowVaulting'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowVaultingTest()
        {
            // TODO unit test for the property 'AllowVaulting'
        }
        /// <summary>
        /// Test the property 'AllowVaultingMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowVaultingMetadataTest()
        {
            // TODO unit test for the property 'AllowVaultingMetadata'
        }
        /// <summary>
        /// Test the property 'AllowWetSigningOverride'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowWetSigningOverrideTest()
        {
            // TODO unit test for the property 'AllowWetSigningOverride'
        }
        /// <summary>
        /// Test the property 'AllowWetSigningOverrideMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowWetSigningOverrideMetadataTest()
        {
            // TODO unit test for the property 'AllowWetSigningOverrideMetadata'
        }
        /// <summary>
        /// Test the property 'CanCreateWorkspaces'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CanCreateWorkspacesTest()
        {
            // TODO unit test for the property 'CanCreateWorkspaces'
        }
        /// <summary>
        /// Test the property 'CanCreateWorkspacesMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CanCreateWorkspacesMetadataTest()
        {
            // TODO unit test for the property 'CanCreateWorkspacesMetadata'
        }
        /// <summary>
        /// Test the property 'DisableDocumentUpload'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DisableDocumentUploadTest()
        {
            // TODO unit test for the property 'DisableDocumentUpload'
        }
        /// <summary>
        /// Test the property 'DisableDocumentUploadMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DisableDocumentUploadMetadataTest()
        {
            // TODO unit test for the property 'DisableDocumentUploadMetadata'
        }
        /// <summary>
        /// Test the property 'DisableOtherActions'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DisableOtherActionsTest()
        {
            // TODO unit test for the property 'DisableOtherActions'
        }
        /// <summary>
        /// Test the property 'DisableOtherActionsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DisableOtherActionsMetadataTest()
        {
            // TODO unit test for the property 'DisableOtherActionsMetadata'
        }
        /// <summary>
        /// Test the property 'EnableApiRequestLogging'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableApiRequestLoggingTest()
        {
            // TODO unit test for the property 'EnableApiRequestLogging'
        }
        /// <summary>
        /// Test the property 'EnableApiRequestLoggingMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableApiRequestLoggingMetadataTest()
        {
            // TODO unit test for the property 'EnableApiRequestLoggingMetadata'
        }
        /// <summary>
        /// Test the property 'EnableRecipientViewingNotifications'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableRecipientViewingNotificationsTest()
        {
            // TODO unit test for the property 'EnableRecipientViewingNotifications'
        }
        /// <summary>
        /// Test the property 'EnableRecipientViewingNotificationsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableRecipientViewingNotificationsMetadataTest()
        {
            // TODO unit test for the property 'EnableRecipientViewingNotificationsMetadata'
        }
        /// <summary>
        /// Test the property 'EnableSequentialSigningInterface'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableSequentialSigningInterfaceTest()
        {
            // TODO unit test for the property 'EnableSequentialSigningInterface'
        }
        /// <summary>
        /// Test the property 'EnableSequentialSigningInterfaceMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableSequentialSigningInterfaceMetadataTest()
        {
            // TODO unit test for the property 'EnableSequentialSigningInterfaceMetadata'
        }
        /// <summary>
        /// Test the property 'EnableTransactionPointIntegration'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableTransactionPointIntegrationTest()
        {
            // TODO unit test for the property 'EnableTransactionPointIntegration'
        }
        /// <summary>
        /// Test the property 'EnableTransactionPointIntegrationMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableTransactionPointIntegrationMetadataTest()
        {
            // TODO unit test for the property 'EnableTransactionPointIntegrationMetadata'
        }
        /// <summary>
        /// Test the property 'PowerFormRole'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PowerFormRoleTest()
        {
            // TODO unit test for the property 'PowerFormRole'
        }
        /// <summary>
        /// Test the property 'PowerFormRoleMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PowerFormRoleMetadataTest()
        {
            // TODO unit test for the property 'PowerFormRoleMetadata'
        }
        /// <summary>
        /// Test the property 'ReceiveCompletedSelfSignedDocumentsAsEmailLinks'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReceiveCompletedSelfSignedDocumentsAsEmailLinksTest()
        {
            // TODO unit test for the property 'ReceiveCompletedSelfSignedDocumentsAsEmailLinks'
        }
        /// <summary>
        /// Test the property 'ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadataTest()
        {
            // TODO unit test for the property 'ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata'
        }
        /// <summary>
        /// Test the property 'SupplementalDocumentsMustAccept'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupplementalDocumentsMustAcceptTest()
        {
            // TODO unit test for the property 'SupplementalDocumentsMustAccept'
        }
        /// <summary>
        /// Test the property 'SupplementalDocumentsMustAcceptMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupplementalDocumentsMustAcceptMetadataTest()
        {
            // TODO unit test for the property 'SupplementalDocumentsMustAcceptMetadata'
        }
        /// <summary>
        /// Test the property 'SupplementalDocumentsMustRead'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupplementalDocumentsMustReadTest()
        {
            // TODO unit test for the property 'SupplementalDocumentsMustRead'
        }
        /// <summary>
        /// Test the property 'SupplementalDocumentsMustReadMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupplementalDocumentsMustReadMetadataTest()
        {
            // TODO unit test for the property 'SupplementalDocumentsMustReadMetadata'
        }
        /// <summary>
        /// Test the property 'SupplementalDocumentsMustView'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupplementalDocumentsMustViewTest()
        {
            // TODO unit test for the property 'SupplementalDocumentsMustView'
        }
        /// <summary>
        /// Test the property 'SupplementalDocumentsMustViewMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupplementalDocumentsMustViewMetadataTest()
        {
            // TODO unit test for the property 'SupplementalDocumentsMustViewMetadata'
        }
        /// <summary>
        /// Test the property 'UseNewDocuSignExperienceInterface'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UseNewDocuSignExperienceInterfaceTest()
        {
            // TODO unit test for the property 'UseNewDocuSignExperienceInterface'
        }
        /// <summary>
        /// Test the property 'UseNewDocuSignExperienceInterfaceMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UseNewDocuSignExperienceInterfaceMetadataTest()
        {
            // TODO unit test for the property 'UseNewDocuSignExperienceInterfaceMetadata'
        }
        /// <summary>
        /// Test the property 'UseNewSendingInterface'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UseNewSendingInterfaceTest()
        {
            // TODO unit test for the property 'UseNewSendingInterface'
        }
        /// <summary>
        /// Test the property 'UseNewSendingInterfaceMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UseNewSendingInterfaceMetadataTest()
        {
            // TODO unit test for the property 'UseNewSendingInterfaceMetadata'
        }
        /// <summary>
        /// Test the property 'VaultingMode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void VaultingModeTest()
        {
            // TODO unit test for the property 'VaultingMode'
        }
        /// <summary>
        /// Test the property 'VaultingModeMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void VaultingModeMetadataTest()
        {
            // TODO unit test for the property 'VaultingModeMetadata'
        }

    }

}
