/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing AccountPasswordStrengthTypeOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class AccountPasswordStrengthTypeOptionTests
    {
        // TODO uncomment below to declare an instance variable for AccountPasswordStrengthTypeOption
        //private AccountPasswordStrengthTypeOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountPasswordStrengthTypeOption
            //instance = new AccountPasswordStrengthTypeOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountPasswordStrengthTypeOption
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountPasswordStrengthTypeOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountPasswordStrengthTypeOption
            //NUnit.Framework.Assert.IsInstanceOf<AccountPasswordStrengthTypeOption> (instance, "variable 'instance' is a AccountPasswordStrengthTypeOption");
        }

        /// <summary>
        /// Test the property 'MinimumLength'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void MinimumLengthTest()
        {
            // TODO unit test for the property 'MinimumLength'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PasswordIncludeDigit'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordIncludeDigitTest()
        {
            // TODO unit test for the property 'PasswordIncludeDigit'
        }
        /// <summary>
        /// Test the property 'PasswordIncludeDigitOrSpecialCharacter'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordIncludeDigitOrSpecialCharacterTest()
        {
            // TODO unit test for the property 'PasswordIncludeDigitOrSpecialCharacter'
        }
        /// <summary>
        /// Test the property 'PasswordIncludeLowerCase'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordIncludeLowerCaseTest()
        {
            // TODO unit test for the property 'PasswordIncludeLowerCase'
        }
        /// <summary>
        /// Test the property 'PasswordIncludeSpecialCharacter'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordIncludeSpecialCharacterTest()
        {
            // TODO unit test for the property 'PasswordIncludeSpecialCharacter'
        }
        /// <summary>
        /// Test the property 'PasswordIncludeUpperCase'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordIncludeUpperCaseTest()
        {
            // TODO unit test for the property 'PasswordIncludeUpperCase'
        }

    }

}
