/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing AccountBillingPlan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class AccountBillingPlanTests
    {
        // TODO uncomment below to declare an instance variable for AccountBillingPlan
        //private AccountBillingPlan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountBillingPlan
            //instance = new AccountBillingPlan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountBillingPlan
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountBillingPlanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountBillingPlan
            //NUnit.Framework.Assert.IsInstanceOf<AccountBillingPlan> (instance, "variable 'instance' is a AccountBillingPlan");
        }

        /// <summary>
        /// Test the property 'AddOns'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AddOnsTest()
        {
            // TODO unit test for the property 'AddOns'
        }
        /// <summary>
        /// Test the property 'CanCancelRenewal'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CanCancelRenewalTest()
        {
            // TODO unit test for the property 'CanCancelRenewal'
        }
        /// <summary>
        /// Test the property 'CanUpgrade'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CanUpgradeTest()
        {
            // TODO unit test for the property 'CanUpgrade'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'EnableSupport'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableSupportTest()
        {
            // TODO unit test for the property 'EnableSupport'
        }
        /// <summary>
        /// Test the property 'IncludedSeats'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludedSeatsTest()
        {
            // TODO unit test for the property 'IncludedSeats'
        }
        /// <summary>
        /// Test the property 'IncrementalSeats'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncrementalSeatsTest()
        {
            // TODO unit test for the property 'IncrementalSeats'
        }
        /// <summary>
        /// Test the property 'IsDowngrade'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsDowngradeTest()
        {
            // TODO unit test for the property 'IsDowngrade'
        }
        /// <summary>
        /// Test the property 'OtherDiscountPercent'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OtherDiscountPercentTest()
        {
            // TODO unit test for the property 'OtherDiscountPercent'
        }
        /// <summary>
        /// Test the property 'PaymentCycle'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PaymentCycleTest()
        {
            // TODO unit test for the property 'PaymentCycle'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PerSeatPrice'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PerSeatPriceTest()
        {
            // TODO unit test for the property 'PerSeatPrice'
        }
        /// <summary>
        /// Test the property 'PlanClassification'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanClassificationTest()
        {
            // TODO unit test for the property 'PlanClassification'
        }
        /// <summary>
        /// Test the property 'PlanFeatureSets'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanFeatureSetsTest()
        {
            // TODO unit test for the property 'PlanFeatureSets'
        }
        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }
        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }
        /// <summary>
        /// Test the property 'RenewalStatus'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RenewalStatusTest()
        {
            // TODO unit test for the property 'RenewalStatus'
        }
        /// <summary>
        /// Test the property 'SeatDiscounts'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SeatDiscountsTest()
        {
            // TODO unit test for the property 'SeatDiscounts'
        }
        /// <summary>
        /// Test the property 'SupportIncidentFee'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupportIncidentFeeTest()
        {
            // TODO unit test for the property 'SupportIncidentFee'
        }
        /// <summary>
        /// Test the property 'SupportPlanFee'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SupportPlanFeeTest()
        {
            // TODO unit test for the property 'SupportPlanFee'
        }

    }

}
