/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing AccountSignatureProvider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class AccountSignatureProviderTests
    {
        // TODO uncomment below to declare an instance variable for AccountSignatureProvider
        //private AccountSignatureProvider instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountSignatureProvider
            //instance = new AccountSignatureProvider();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountSignatureProvider
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountSignatureProviderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountSignatureProvider
            //NUnit.Framework.Assert.IsInstanceOf<AccountSignatureProvider> (instance, "variable 'instance' is a AccountSignatureProvider");
        }

        /// <summary>
        /// Test the property 'IsRequired'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsRequiredTest()
        {
            // TODO unit test for the property 'IsRequired'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'SignatureProviderDisplayName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignatureProviderDisplayNameTest()
        {
            // TODO unit test for the property 'SignatureProviderDisplayName'
        }
        /// <summary>
        /// Test the property 'SignatureProviderId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignatureProviderIdTest()
        {
            // TODO unit test for the property 'SignatureProviderId'
        }
        /// <summary>
        /// Test the property 'SignatureProviderName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignatureProviderNameTest()
        {
            // TODO unit test for the property 'SignatureProviderName'
        }
        /// <summary>
        /// Test the property 'SignatureProviderOptionsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignatureProviderOptionsMetadataTest()
        {
            // TODO unit test for the property 'SignatureProviderOptionsMetadata'
        }
        /// <summary>
        /// Test the property 'SignatureProviderRequiredOptions'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignatureProviderRequiredOptionsTest()
        {
            // TODO unit test for the property 'SignatureProviderRequiredOptions'
        }

    }

}
