/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing AppStoreProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class AppStoreProductTests
    {
        // TODO uncomment below to declare an instance variable for AppStoreProduct
        //private AppStoreProduct instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppStoreProduct
            //instance = new AppStoreProduct();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppStoreProduct
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AppStoreProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppStoreProduct
            //NUnit.Framework.Assert.IsInstanceOf<AppStoreProduct> (instance, "variable 'instance' is a AppStoreProduct");
        }

        /// <summary>
        /// Test the property 'MarketPlace'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void MarketPlaceTest()
        {
            // TODO unit test for the property 'MarketPlace'
        }
        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

    }

}
