/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Attachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class AttachmentTests
    {
        // TODO uncomment below to declare an instance variable for Attachment
        //private Attachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Attachment
            //instance = new Attachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Attachment
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Attachment
            //NUnit.Framework.Assert.IsInstanceOf<Attachment> (instance, "variable 'instance' is a Attachment");
        }

        /// <summary>
        /// Test the property 'AccessControl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccessControlTest()
        {
            // TODO unit test for the property 'AccessControl'
        }
        /// <summary>
        /// Test the property 'AttachmentId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AttachmentIdTest()
        {
            // TODO unit test for the property 'AttachmentId'
        }
        /// <summary>
        /// Test the property 'AttachmentType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AttachmentTypeTest()
        {
            // TODO unit test for the property 'AttachmentType'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RemoteUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RemoteUrlTest()
        {
            // TODO unit test for the property 'RemoteUrl'
        }

    }

}
