/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing BillingInvoiceItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class BillingInvoiceItemTests
    {
        // TODO uncomment below to declare an instance variable for BillingInvoiceItem
        //private BillingInvoiceItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingInvoiceItem
            //instance = new BillingInvoiceItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingInvoiceItem
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BillingInvoiceItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingInvoiceItem
            //NUnit.Framework.Assert.IsInstanceOf<BillingInvoiceItem> (instance, "variable 'instance' is a BillingInvoiceItem");
        }

        /// <summary>
        /// Test the property 'ChargeAmount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ChargeAmountTest()
        {
            // TODO unit test for the property 'ChargeAmount'
        }
        /// <summary>
        /// Test the property 'ChargeName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ChargeNameTest()
        {
            // TODO unit test for the property 'ChargeName'
        }
        /// <summary>
        /// Test the property 'InvoiceItemId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void InvoiceItemIdTest()
        {
            // TODO unit test for the property 'InvoiceItemId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }

    }

}
