/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing BillingPlanUpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class BillingPlanUpdateResponseTests
    {
        // TODO uncomment below to declare an instance variable for BillingPlanUpdateResponse
        //private BillingPlanUpdateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingPlanUpdateResponse
            //instance = new BillingPlanUpdateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingPlanUpdateResponse
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BillingPlanUpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingPlanUpdateResponse
            //NUnit.Framework.Assert.IsInstanceOf<BillingPlanUpdateResponse> (instance, "variable 'instance' is a BillingPlanUpdateResponse");
        }

        /// <summary>
        /// Test the property 'BillingPlanPreview'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BillingPlanPreviewTest()
        {
            // TODO unit test for the property 'BillingPlanPreview'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'IncludedSeats'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludedSeatsTest()
        {
            // TODO unit test for the property 'IncludedSeats'
        }
        /// <summary>
        /// Test the property 'PaymentCycle'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PaymentCycleTest()
        {
            // TODO unit test for the property 'PaymentCycle'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }
        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }

    }

}
