/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing BrandsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class BrandsResponseTests
    {
        // TODO uncomment below to declare an instance variable for BrandsResponse
        //private BrandsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandsResponse
            //instance = new BrandsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandsResponse
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandsResponse
            //NUnit.Framework.Assert.IsInstanceOf<BrandsResponse> (instance, "variable 'instance' is a BrandsResponse");
        }

        /// <summary>
        /// Test the property 'Brands'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandsTest()
        {
            // TODO unit test for the property 'Brands'
        }
        /// <summary>
        /// Test the property 'RecipientBrandIdDefault'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientBrandIdDefaultTest()
        {
            // TODO unit test for the property 'RecipientBrandIdDefault'
        }
        /// <summary>
        /// Test the property 'SenderBrandIdDefault'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderBrandIdDefaultTest()
        {
            // TODO unit test for the property 'SenderBrandIdDefault'
        }

    }

}
