/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Brand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class BrandTests
    {
        // TODO uncomment below to declare an instance variable for Brand
        //private Brand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Brand
            //instance = new Brand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Brand
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Brand
            //NUnit.Framework.Assert.IsInstanceOf<Brand> (instance, "variable 'instance' is a Brand");
        }

        /// <summary>
        /// Test the property 'BrandCompany'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandCompanyTest()
        {
            // TODO unit test for the property 'BrandCompany'
        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandIdTest()
        {
            // TODO unit test for the property 'BrandId'
        }
        /// <summary>
        /// Test the property 'BrandName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandNameTest()
        {
            // TODO unit test for the property 'BrandName'
        }
        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }
        /// <summary>
        /// Test the property 'EmailContent'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailContentTest()
        {
            // TODO unit test for the property 'EmailContent'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'IsOverridingCompanyName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsOverridingCompanyNameTest()
        {
            // TODO unit test for the property 'IsOverridingCompanyName'
        }
        /// <summary>
        /// Test the property 'IsSendingDefault'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsSendingDefaultTest()
        {
            // TODO unit test for the property 'IsSendingDefault'
        }
        /// <summary>
        /// Test the property 'IsSigningDefault'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsSigningDefaultTest()
        {
            // TODO unit test for the property 'IsSigningDefault'
        }
        /// <summary>
        /// Test the property 'LandingPages'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LandingPagesTest()
        {
            // TODO unit test for the property 'LandingPages'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Logos'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LogosTest()
        {
            // TODO unit test for the property 'Logos'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

    }

}
