/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing BrandEmailContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class BrandEmailContentTests
    {
        // TODO uncomment below to declare an instance variable for BrandEmailContent
        //private BrandEmailContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandEmailContent
            //instance = new BrandEmailContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandEmailContent
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BrandEmailContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandEmailContent
            //NUnit.Framework.Assert.IsInstanceOf<BrandEmailContent> (instance, "variable 'instance' is a BrandEmailContent");
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'EmailContentType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailContentTypeTest()
        {
            // TODO unit test for the property 'EmailContentType'
        }
        /// <summary>
        /// Test the property 'EmailToLink'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailToLinkTest()
        {
            // TODO unit test for the property 'EmailToLink'
        }
        /// <summary>
        /// Test the property 'LinkText'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LinkTextTest()
        {
            // TODO unit test for the property 'LinkText'
        }

    }

}
