/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ChunkedUploadRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ChunkedUploadRequestTests
    {
        // TODO uncomment below to declare an instance variable for ChunkedUploadRequest
        //private ChunkedUploadRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChunkedUploadRequest
            //instance = new ChunkedUploadRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChunkedUploadRequest
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ChunkedUploadRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChunkedUploadRequest
            //NUnit.Framework.Assert.IsInstanceOf<ChunkedUploadRequest> (instance, "variable 'instance' is a ChunkedUploadRequest");
        }

        /// <summary>
        /// Test the property 'ChunkedUploadId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ChunkedUploadIdTest()
        {
            // TODO unit test for the property 'ChunkedUploadId'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
