/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing CompositeTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class CompositeTemplateTests
    {
        // TODO uncomment below to declare an instance variable for CompositeTemplate
        //private CompositeTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompositeTemplate
            //instance = new CompositeTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompositeTemplate
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CompositeTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompositeTemplate
            //NUnit.Framework.Assert.IsInstanceOf<CompositeTemplate> (instance, "variable 'instance' is a CompositeTemplate");
        }

        /// <summary>
        /// Test the property 'CompositeTemplateId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CompositeTemplateIdTest()
        {
            // TODO unit test for the property 'CompositeTemplateId'
        }
        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'InlineTemplates'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void InlineTemplatesTest()
        {
            // TODO unit test for the property 'InlineTemplates'
        }
        /// <summary>
        /// Test the property 'PdfMetaDataTemplateSequence'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PdfMetaDataTemplateSequenceTest()
        {
            // TODO unit test for the property 'PdfMetaDataTemplateSequence'
        }
        /// <summary>
        /// Test the property 'ServerTemplates'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ServerTemplatesTest()
        {
            // TODO unit test for the property 'ServerTemplates'
        }

    }

}
