/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ConnectFailureResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ConnectFailureResultTests
    {
        // TODO uncomment below to declare an instance variable for ConnectFailureResult
        //private ConnectFailureResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectFailureResult
            //instance = new ConnectFailureResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectFailureResult
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectFailureResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectFailureResult
            //NUnit.Framework.Assert.IsInstanceOf<ConnectFailureResult> (instance, "variable 'instance' is a ConnectFailureResult");
        }

        /// <summary>
        /// Test the property 'ConfigId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConfigIdTest()
        {
            // TODO unit test for the property 'ConfigId'
        }
        /// <summary>
        /// Test the property 'ConfigUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConfigUrlTest()
        {
            // TODO unit test for the property 'ConfigUrl'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }

    }

}
