/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ConnectLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ConnectLogTests
    {
        // TODO uncomment below to declare an instance variable for ConnectLog
        //private ConnectLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectLog
            //instance = new ConnectLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectLog
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectLog
            //NUnit.Framework.Assert.IsInstanceOf<ConnectLog> (instance, "variable 'instance' is a ConnectLog");
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'ConfigUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConfigUrlTest()
        {
            // TODO unit test for the property 'ConfigUrl'
        }
        /// <summary>
        /// Test the property 'ConnectDebugLog'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectDebugLogTest()
        {
            // TODO unit test for the property 'ConnectDebugLog'
        }
        /// <summary>
        /// Test the property 'ConnectId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectIdTest()
        {
            // TODO unit test for the property 'ConnectId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'FailureId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FailureIdTest()
        {
            // TODO unit test for the property 'FailureId'
        }
        /// <summary>
        /// Test the property 'FailureUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FailureUriTest()
        {
            // TODO unit test for the property 'FailureUri'
        }
        /// <summary>
        /// Test the property 'LastTry'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastTryTest()
        {
            // TODO unit test for the property 'LastTry'
        }
        /// <summary>
        /// Test the property 'LogId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LogIdTest()
        {
            // TODO unit test for the property 'LogId'
        }
        /// <summary>
        /// Test the property 'LogUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LogUriTest()
        {
            // TODO unit test for the property 'LogUri'
        }
        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }
        /// <summary>
        /// Test the property 'RetryUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RetryUriTest()
        {
            // TODO unit test for the property 'RetryUri'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
