/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ConnectCustomConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ConnectCustomConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for ConnectCustomConfiguration
        //private ConnectCustomConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectCustomConfiguration
            //instance = new ConnectCustomConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectCustomConfiguration
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectCustomConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectCustomConfiguration
            //NUnit.Framework.Assert.IsInstanceOf<ConnectCustomConfiguration> (instance, "variable 'instance' is a ConnectCustomConfiguration");
        }

        /// <summary>
        /// Test the property 'AllowEnvelopePublish'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowEnvelopePublishTest()
        {
            // TODO unit test for the property 'AllowEnvelopePublish'
        }
        /// <summary>
        /// Test the property 'AllUsers'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllUsersTest()
        {
            // TODO unit test for the property 'AllUsers'
        }
        /// <summary>
        /// Test the property 'ConfigurationType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConfigurationTypeTest()
        {
            // TODO unit test for the property 'ConfigurationType'
        }
        /// <summary>
        /// Test the property 'ConnectId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectIdTest()
        {
            // TODO unit test for the property 'ConnectId'
        }
        /// <summary>
        /// Test the property 'EnableLog'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableLogTest()
        {
            // TODO unit test for the property 'EnableLog'
        }
        /// <summary>
        /// Test the property 'EnvelopeEvents'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeEventsTest()
        {
            // TODO unit test for the property 'EnvelopeEvents'
        }
        /// <summary>
        /// Test the property 'IncludeCertificateOfCompletion'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeCertificateOfCompletionTest()
        {
            // TODO unit test for the property 'IncludeCertificateOfCompletion'
        }
        /// <summary>
        /// Test the property 'IncludeCertSoapHeader'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeCertSoapHeaderTest()
        {
            // TODO unit test for the property 'IncludeCertSoapHeader'
        }
        /// <summary>
        /// Test the property 'IncludeDocumentFields'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeDocumentFieldsTest()
        {
            // TODO unit test for the property 'IncludeDocumentFields'
        }
        /// <summary>
        /// Test the property 'IncludeDocuments'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeDocumentsTest()
        {
            // TODO unit test for the property 'IncludeDocuments'
        }
        /// <summary>
        /// Test the property 'IncludeEnvelopeVoidReason'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeEnvelopeVoidReasonTest()
        {
            // TODO unit test for the property 'IncludeEnvelopeVoidReason'
        }
        /// <summary>
        /// Test the property 'IncludeSenderAccountasCustomField'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeSenderAccountasCustomFieldTest()
        {
            // TODO unit test for the property 'IncludeSenderAccountasCustomField'
        }
        /// <summary>
        /// Test the property 'IncludeTimeZoneInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeTimeZoneInformationTest()
        {
            // TODO unit test for the property 'IncludeTimeZoneInformation'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecipientEvents'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientEventsTest()
        {
            // TODO unit test for the property 'RecipientEvents'
        }
        /// <summary>
        /// Test the property 'RequiresAcknowledgement'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RequiresAcknowledgementTest()
        {
            // TODO unit test for the property 'RequiresAcknowledgement'
        }
        /// <summary>
        /// Test the property 'SignMessageWithX509Certificate'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignMessageWithX509CertificateTest()
        {
            // TODO unit test for the property 'SignMessageWithX509Certificate'
        }
        /// <summary>
        /// Test the property 'SoapNamespace'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SoapNamespaceTest()
        {
            // TODO unit test for the property 'SoapNamespace'
        }
        /// <summary>
        /// Test the property 'UrlToPublishTo'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UrlToPublishToTest()
        {
            // TODO unit test for the property 'UrlToPublishTo'
        }
        /// <summary>
        /// Test the property 'UserIds'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserIdsTest()
        {
            // TODO unit test for the property 'UserIds'
        }
        /// <summary>
        /// Test the property 'UseSoapInterface'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UseSoapInterfaceTest()
        {
            // TODO unit test for the property 'UseSoapInterface'
        }

    }

}
