/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ConnectLogs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ConnectLogsTests
    {
        // TODO uncomment below to declare an instance variable for ConnectLogs
        //private ConnectLogs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectLogs
            //instance = new ConnectLogs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectLogs
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectLogsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectLogs
            //NUnit.Framework.Assert.IsInstanceOf<ConnectLogs> (instance, "variable 'instance' is a ConnectLogs");
        }

        /// <summary>
        /// Test the property 'Failures'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FailuresTest()
        {
            // TODO unit test for the property 'Failures'
        }
        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }
        /// <summary>
        /// Test the property 'TotalRecords'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TotalRecordsTest()
        {
            // TODO unit test for the property 'TotalRecords'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
