/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ConnectDebugLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ConnectDebugLogTests
    {
        // TODO uncomment below to declare an instance variable for ConnectDebugLog
        //private ConnectDebugLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectDebugLog
            //instance = new ConnectDebugLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectDebugLog
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectDebugLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectDebugLog
            //NUnit.Framework.Assert.IsInstanceOf<ConnectDebugLog> (instance, "variable 'instance' is a ConnectDebugLog");
        }

        /// <summary>
        /// Test the property 'ConnectConfig'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectConfigTest()
        {
            // TODO unit test for the property 'ConnectConfig'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'EventDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EventDateTimeTest()
        {
            // TODO unit test for the property 'EventDateTime'
        }
        /// <summary>
        /// Test the property 'EventDescription'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EventDescriptionTest()
        {
            // TODO unit test for the property 'EventDescription'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

    }

}
