/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Contact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ContactTests
    {
        // TODO uncomment below to declare an instance variable for Contact
        //private Contact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Contact
            //instance = new Contact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Contact
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Contact
            //NUnit.Framework.Assert.IsInstanceOf<Contact> (instance, "variable 'instance' is a Contact");
        }

        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }
        /// <summary>
        /// Test the property 'ContactUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ContactUriTest()
        {
            // TODO unit test for the property 'ContactUri'
        }
        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'SigningGroup'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SigningGroupTest()
        {
            // TODO unit test for the property 'SigningGroup'
        }
        /// <summary>
        /// Test the property 'SigningGroupName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SigningGroupNameTest()
        {
            // TODO unit test for the property 'SigningGroupName'
        }

    }

}
