/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing CreditCardInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class CreditCardInformationTests
    {
        // TODO uncomment below to declare an instance variable for CreditCardInformation
        //private CreditCardInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditCardInformation
            //instance = new CreditCardInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditCardInformation
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreditCardInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditCardInformation
            //NUnit.Framework.Assert.IsInstanceOf<CreditCardInformation> (instance, "variable 'instance' is a CreditCardInformation");
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }
        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }
        /// <summary>
        /// Test the property 'ExpirationMonth'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpirationMonthTest()
        {
            // TODO unit test for the property 'ExpirationMonth'
        }
        /// <summary>
        /// Test the property 'ExpirationYear'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpirationYearTest()
        {
            // TODO unit test for the property 'ExpirationYear'
        }
        /// <summary>
        /// Test the property 'NameOnCard'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameOnCardTest()
        {
            // TODO unit test for the property 'NameOnCard'
        }

    }

}
