/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Credential
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class CredentialTests
    {
        // TODO uncomment below to declare an instance variable for Credential
        //private Credential instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Credential
            //instance = new Credential();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Credential
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CredentialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Credential
            //NUnit.Framework.Assert.IsInstanceOf<Credential> (instance, "variable 'instance' is a Credential");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
