/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing CustomField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class CustomFieldTests
    {
        // TODO uncomment below to declare an instance variable for CustomField
        //private CustomField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomField
            //instance = new CustomField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomField
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CustomFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomField
            //NUnit.Framework.Assert.IsInstanceOf<CustomField> (instance, "variable 'instance' is a CustomField");
        }

        /// <summary>
        /// Test the property 'CustomFieldType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CustomFieldTypeTest()
        {
            // TODO unit test for the property 'CustomFieldType'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'FieldId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FieldIdTest()
        {
            // TODO unit test for the property 'FieldId'
        }
        /// <summary>
        /// Test the property 'ListItems'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ListItemsTest()
        {
            // TODO unit test for the property 'ListItems'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'Show'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ShowTest()
        {
            // TODO unit test for the property 'Show'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
