/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing DateStampProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class DateStampPropertiesTests
    {
        // TODO uncomment below to declare an instance variable for DateStampProperties
        //private DateStampProperties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of DateStampProperties
            //instance = new DateStampProperties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DateStampProperties
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DateStampPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DateStampProperties
            //NUnit.Framework.Assert.IsInstanceOf<DateStampProperties> (instance, "variable 'instance' is a DateStampProperties");
        }

        /// <summary>
        /// Test the property 'DateAreaHeight'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DateAreaHeightTest()
        {
            // TODO unit test for the property 'DateAreaHeight'
        }
        /// <summary>
        /// Test the property 'DateAreaWidth'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DateAreaWidthTest()
        {
            // TODO unit test for the property 'DateAreaWidth'
        }
        /// <summary>
        /// Test the property 'DateAreaX'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DateAreaXTest()
        {
            // TODO unit test for the property 'DateAreaX'
        }
        /// <summary>
        /// Test the property 'DateAreaY'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DateAreaYTest()
        {
            // TODO unit test for the property 'DateAreaY'
        }

    }

}
