/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing DobInformationInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class DobInformationInputTests
    {
        // TODO uncomment below to declare an instance variable for DobInformationInput
        //private DobInformationInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of DobInformationInput
            //instance = new DobInformationInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DobInformationInput
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DobInformationInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DobInformationInput
            //NUnit.Framework.Assert.IsInstanceOf<DobInformationInput> (instance, "variable 'instance' is a DobInformationInput");
        }

        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'DisplayLevelCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DisplayLevelCodeTest()
        {
            // TODO unit test for the property 'DisplayLevelCode'
        }
        /// <summary>
        /// Test the property 'ReceiveInResponse'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReceiveInResponseTest()
        {
            // TODO unit test for the property 'ReceiveInResponse'
        }

    }

}
