/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing DocumentVisibility
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class DocumentVisibilityTests
    {
        // TODO uncomment below to declare an instance variable for DocumentVisibility
        //private DocumentVisibility instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentVisibility
            //instance = new DocumentVisibility();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentVisibility
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentVisibilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentVisibility
            //NUnit.Framework.Assert.IsInstanceOf<DocumentVisibility> (instance, "variable 'instance' is a DocumentVisibility");
        }

        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'RecipientId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientIdTest()
        {
            // TODO unit test for the property 'RecipientId'
        }
        /// <summary>
        /// Test the property 'Rights'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RightsTest()
        {
            // TODO unit test for the property 'Rights'
        }
        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }

    }

}
