/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ENoteConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ENoteConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for ENoteConfiguration
        //private ENoteConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ENoteConfiguration
            //instance = new ENoteConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ENoteConfiguration
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ENoteConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ENoteConfiguration
            //NUnit.Framework.Assert.IsInstanceOf<ENoteConfiguration> (instance, "variable 'instance' is a ENoteConfiguration");
        }

        /// <summary>
        /// Test the property 'ConnectConfigured'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConnectConfiguredTest()
        {
            // TODO unit test for the property 'ConnectConfigured'
        }
        /// <summary>
        /// Test the property 'ENoteConfigured'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ENoteConfiguredTest()
        {
            // TODO unit test for the property 'ENoteConfigured'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
