/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing EnvelopeTransactionStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class EnvelopeTransactionStatusTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeTransactionStatus
        //private EnvelopeTransactionStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeTransactionStatus
            //instance = new EnvelopeTransactionStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeTransactionStatus
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeTransactionStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeTransactionStatus
            //NUnit.Framework.Assert.IsInstanceOf<EnvelopeTransactionStatus> (instance, "variable 'instance' is a EnvelopeTransactionStatus");
        }

        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }

    }

}
