/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing EnvelopeDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class EnvelopeDocumentTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeDocument
        //private EnvelopeDocument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeDocument
            //instance = new EnvelopeDocument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeDocument
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeDocument
            //NUnit.Framework.Assert.IsInstanceOf<EnvelopeDocument> (instance, "variable 'instance' is a EnvelopeDocument");
        }

        /// <summary>
        /// Test the property 'AttachmentTabId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AttachmentTabIdTest()
        {
            // TODO unit test for the property 'AttachmentTabId'
        }
        /// <summary>
        /// Test the property 'AvailableDocumentTypes'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AvailableDocumentTypesTest()
        {
            // TODO unit test for the property 'AvailableDocumentTypes'
        }
        /// <summary>
        /// Test the property 'ContainsPdfFormFields'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ContainsPdfFormFieldsTest()
        {
            // TODO unit test for the property 'ContainsPdfFormFields'
        }
        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }
        /// <summary>
        /// Test the property 'DocumentFields'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentFieldsTest()
        {
            // TODO unit test for the property 'DocumentFields'
        }
        /// <summary>
        /// Test the property 'DocumentGroup'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentGroupTest()
        {
            // TODO unit test for the property 'DocumentGroup'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'IncludeInDownload'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludeInDownloadTest()
        {
            // TODO unit test for the property 'IncludeInDownload'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }
        /// <summary>
        /// Test the property 'SignerMustAcknowledge'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignerMustAcknowledgeTest()
        {
            // TODO unit test for the property 'SignerMustAcknowledge'
        }
        /// <summary>
        /// Test the property 'TemplateLocked'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateLockedTest()
        {
            // TODO unit test for the property 'TemplateLocked'
        }
        /// <summary>
        /// Test the property 'TemplateRequired'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateRequiredTest()
        {
            // TODO unit test for the property 'TemplateRequired'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
