/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing EnvelopeTemplateDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class EnvelopeTemplateDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeTemplateDefinition
        //private EnvelopeTemplateDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeTemplateDefinition
            //instance = new EnvelopeTemplateDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeTemplateDefinition
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeTemplateDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeTemplateDefinition
            //NUnit.Framework.Assert.IsInstanceOf<EnvelopeTemplateDefinition> (instance, "variable 'instance' is a EnvelopeTemplateDefinition");
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FolderId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FolderIdTest()
        {
            // TODO unit test for the property 'FolderId'
        }
        /// <summary>
        /// Test the property 'FolderName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FolderNameTest()
        {
            // TODO unit test for the property 'FolderName'
        }
        /// <summary>
        /// Test the property 'FolderUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FolderUriTest()
        {
            // TODO unit test for the property 'FolderUri'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'ParentFolderUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ParentFolderUriTest()
        {
            // TODO unit test for the property 'ParentFolderUri'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
