/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Expirations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ExpirationsTests
    {
        // TODO uncomment below to declare an instance variable for Expirations
        //private Expirations instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Expirations
            //instance = new Expirations();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Expirations
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpirationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Expirations
            //NUnit.Framework.Assert.IsInstanceOf<Expirations> (instance, "variable 'instance' is a Expirations");
        }

        /// <summary>
        /// Test the property 'ExpireAfter'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpireAfterTest()
        {
            // TODO unit test for the property 'ExpireAfter'
        }
        /// <summary>
        /// Test the property 'ExpireEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpireEnabledTest()
        {
            // TODO unit test for the property 'ExpireEnabled'
        }
        /// <summary>
        /// Test the property 'ExpireWarn'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpireWarnTest()
        {
            // TODO unit test for the property 'ExpireWarn'
        }

    }

}
