/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Filter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class FilterTests
    {
        // TODO uncomment below to declare an instance variable for Filter
        //private Filter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Filter
            //instance = new Filter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Filter
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Filter
            //NUnit.Framework.Assert.IsInstanceOf<Filter> (instance, "variable 'instance' is a Filter");
        }

        /// <summary>
        /// Test the property 'ActionRequired'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ActionRequiredTest()
        {
            // TODO unit test for the property 'ActionRequired'
        }
        /// <summary>
        /// Test the property 'Expires'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpiresTest()
        {
            // TODO unit test for the property 'Expires'
        }
        /// <summary>
        /// Test the property 'FolderIds'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FolderIdsTest()
        {
            // TODO unit test for the property 'FolderIds'
        }
        /// <summary>
        /// Test the property 'FromDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FromDateTimeTest()
        {
            // TODO unit test for the property 'FromDateTime'
        }
        /// <summary>
        /// Test the property 'IsTemplate'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsTemplateTest()
        {
            // TODO unit test for the property 'IsTemplate'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }
        /// <summary>
        /// Test the property 'SearchTarget'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SearchTargetTest()
        {
            // TODO unit test for the property 'SearchTarget'
        }
        /// <summary>
        /// Test the property 'SearchText'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SearchTextTest()
        {
            // TODO unit test for the property 'SearchText'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ToDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ToDateTimeTest()
        {
            // TODO unit test for the property 'ToDateTime'
        }

    }

}
