/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Group
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class GroupTests
    {
        // TODO uncomment below to declare an instance variable for Group
        //private Group instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Group
            //instance = new Group();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Group
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void GroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Group
            //NUnit.Framework.Assert.IsInstanceOf<Group> (instance, "variable 'instance' is a Group");
        }

        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
        /// <summary>
        /// Test the property 'GroupType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void GroupTypeTest()
        {
            // TODO unit test for the property 'GroupType'
        }
        /// <summary>
        /// Test the property 'PermissionProfileId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PermissionProfileIdTest()
        {
            // TODO unit test for the property 'PermissionProfileId'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
