/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing InlineTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class InlineTemplateTests
    {
        // TODO uncomment below to declare an instance variable for InlineTemplate
        //private InlineTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineTemplate
            //instance = new InlineTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineTemplate
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void InlineTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineTemplate
            //NUnit.Framework.Assert.IsInstanceOf<InlineTemplate> (instance, "variable 'instance' is a InlineTemplate");
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'Envelope'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeTest()
        {
            // TODO unit test for the property 'Envelope'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }

    }

}
