/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing LoginAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class LoginAccountTests
    {
        // TODO uncomment below to declare an instance variable for LoginAccount
        //private LoginAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginAccount
            //instance = new LoginAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginAccount
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LoginAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginAccount
            //NUnit.Framework.Assert.IsInstanceOf<LoginAccount> (instance, "variable 'instance' is a LoginAccount");
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountIdGuid'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountIdGuidTest()
        {
            // TODO unit test for the property 'AccountIdGuid'
        }
        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }
        /// <summary>
        /// Test the property 'LoginAccountSettings'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LoginAccountSettingsTest()
        {
            // TODO unit test for the property 'LoginAccountSettings'
        }
        /// <summary>
        /// Test the property 'LoginUserSettings'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LoginUserSettingsTest()
        {
            // TODO unit test for the property 'LoginUserSettings'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SiteDescription'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SiteDescriptionTest()
        {
            // TODO unit test for the property 'SiteDescription'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
