/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing MergeField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class MergeFieldTests
    {
        // TODO uncomment below to declare an instance variable for MergeField
        //private MergeField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of MergeField
            //instance = new MergeField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MergeField
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void MergeFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MergeField
            //NUnit.Framework.Assert.IsInstanceOf<MergeField> (instance, "variable 'instance' is a MergeField");
        }

        /// <summary>
        /// Test the property 'AllowSenderToEdit'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowSenderToEditTest()
        {
            // TODO unit test for the property 'AllowSenderToEdit'
        }
        /// <summary>
        /// Test the property 'ConfigurationType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConfigurationTypeTest()
        {
            // TODO unit test for the property 'ConfigurationType'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Row'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RowTest()
        {
            // TODO unit test for the property 'Row'
        }
        /// <summary>
        /// Test the property 'WriteBack'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WriteBackTest()
        {
            // TODO unit test for the property 'WriteBack'
        }

    }

}
