/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing NewAccountDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class NewAccountDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for NewAccountDefinition
        //private NewAccountDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewAccountDefinition
            //instance = new NewAccountDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewAccountDefinition
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NewAccountDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewAccountDefinition
            //NUnit.Framework.Assert.IsInstanceOf<NewAccountDefinition> (instance, "variable 'instance' is a NewAccountDefinition");
        }

        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'AccountSettings'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountSettingsTest()
        {
            // TODO unit test for the property 'AccountSettings'
        }
        /// <summary>
        /// Test the property 'AddressInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AddressInformationTest()
        {
            // TODO unit test for the property 'AddressInformation'
        }
        /// <summary>
        /// Test the property 'CreditCardInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreditCardInformationTest()
        {
            // TODO unit test for the property 'CreditCardInformation'
        }
        /// <summary>
        /// Test the property 'DistributorCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DistributorCodeTest()
        {
            // TODO unit test for the property 'DistributorCode'
        }
        /// <summary>
        /// Test the property 'DistributorPassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DistributorPasswordTest()
        {
            // TODO unit test for the property 'DistributorPassword'
        }
        /// <summary>
        /// Test the property 'InitialUser'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void InitialUserTest()
        {
            // TODO unit test for the property 'InitialUser'
        }
        /// <summary>
        /// Test the property 'PlanInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanInformationTest()
        {
            // TODO unit test for the property 'PlanInformation'
        }
        /// <summary>
        /// Test the property 'ReferralInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReferralInformationTest()
        {
            // TODO unit test for the property 'ReferralInformation'
        }
        /// <summary>
        /// Test the property 'SocialAccountInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SocialAccountInformationTest()
        {
            // TODO unit test for the property 'SocialAccountInformation'
        }

    }

}
