/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing NewUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class NewUserTests
    {
        // TODO uncomment below to declare an instance variable for NewUser
        //private NewUser instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewUser
            //instance = new NewUser();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewUser
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NewUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewUser
            //NUnit.Framework.Assert.IsInstanceOf<NewUser> (instance, "variable 'instance' is a NewUser");
        }

        /// <summary>
        /// Test the property 'ApiPassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ApiPasswordTest()
        {
            // TODO unit test for the property 'ApiPassword'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'PermissionProfileId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PermissionProfileIdTest()
        {
            // TODO unit test for the property 'PermissionProfileId'
        }
        /// <summary>
        /// Test the property 'PermissionProfileName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PermissionProfileNameTest()
        {
            // TODO unit test for the property 'PermissionProfileName'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'UserStatus'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserStatusTest()
        {
            // TODO unit test for the property 'UserStatus'
        }

    }

}
