/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing NotaryJournal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class NotaryJournalTests
    {
        // TODO uncomment below to declare an instance variable for NotaryJournal
        //private NotaryJournal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotaryJournal
            //instance = new NotaryJournal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotaryJournal
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NotaryJournalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotaryJournal
            //NUnit.Framework.Assert.IsInstanceOf<NotaryJournal> (instance, "variable 'instance' is a NotaryJournal");
        }

        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'DocumentName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentNameTest()
        {
            // TODO unit test for the property 'DocumentName'
        }
        /// <summary>
        /// Test the property 'Jurisdiction'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void JurisdictionTest()
        {
            // TODO unit test for the property 'Jurisdiction'
        }
        /// <summary>
        /// Test the property 'NotaryJournalId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NotaryJournalIdTest()
        {
            // TODO unit test for the property 'NotaryJournalId'
        }
        /// <summary>
        /// Test the property 'NotaryJournalMetaData'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NotaryJournalMetaDataTest()
        {
            // TODO unit test for the property 'NotaryJournalMetaData'
        }
        /// <summary>
        /// Test the property 'SignerName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignerNameTest()
        {
            // TODO unit test for the property 'SignerName'
        }

    }

}
