/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Notification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class NotificationTests
    {
        // TODO uncomment below to declare an instance variable for Notification
        //private Notification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Notification
            //instance = new Notification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Notification
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NotificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Notification
            //NUnit.Framework.Assert.IsInstanceOf<Notification> (instance, "variable 'instance' is a Notification");
        }

        /// <summary>
        /// Test the property 'Expirations'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpirationsTest()
        {
            // TODO unit test for the property 'Expirations'
        }
        /// <summary>
        /// Test the property 'Reminders'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RemindersTest()
        {
            // TODO unit test for the property 'Reminders'
        }
        /// <summary>
        /// Test the property 'UseAccountDefaults'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UseAccountDefaultsTest()
        {
            // TODO unit test for the property 'UseAccountDefaults'
        }

    }

}
