/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing OauthAccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class OauthAccessTests
    {
        // TODO uncomment below to declare an instance variable for OauthAccess
        //private OauthAccess instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of OauthAccess
            //instance = new OauthAccess();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OauthAccess
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OauthAccessInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OauthAccess
            //NUnit.Framework.Assert.IsInstanceOf<OauthAccess> (instance, "variable 'instance' is a OauthAccess");
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }
        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

    }

}
