/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing PermissionProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class PermissionProfileTests
    {
        // TODO uncomment below to declare an instance variable for PermissionProfile
        //private PermissionProfile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of PermissionProfile
            //instance = new PermissionProfile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PermissionProfile
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PermissionProfileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PermissionProfile
            //NUnit.Framework.Assert.IsInstanceOf<PermissionProfile> (instance, "variable 'instance' is a PermissionProfile");
        }

        /// <summary>
        /// Test the property 'ModifiedByUsername'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ModifiedByUsernameTest()
        {
            // TODO unit test for the property 'ModifiedByUsername'
        }
        /// <summary>
        /// Test the property 'ModifiedDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ModifiedDateTimeTest()
        {
            // TODO unit test for the property 'ModifiedDateTime'
        }
        /// <summary>
        /// Test the property 'PermissionProfileId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PermissionProfileIdTest()
        {
            // TODO unit test for the property 'PermissionProfileId'
        }
        /// <summary>
        /// Test the property 'PermissionProfileName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PermissionProfileNameTest()
        {
            // TODO unit test for the property 'PermissionProfileName'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
        /// <summary>
        /// Test the property 'UserCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserCountTest()
        {
            // TODO unit test for the property 'UserCount'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
