/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing PowerForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class PowerFormTests
    {
        // TODO uncomment below to declare an instance variable for PowerForm
        //private PowerForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of PowerForm
            //instance = new PowerForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PowerForm
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PowerFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PowerForm
            //NUnit.Framework.Assert.IsInstanceOf<PowerForm> (instance, "variable 'instance' is a PowerForm");
        }

        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'EmailBody'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailBodyTest()
        {
            // TODO unit test for the property 'EmailBody'
        }
        /// <summary>
        /// Test the property 'EmailSubject'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailSubjectTest()
        {
            // TODO unit test for the property 'EmailSubject'
        }
        /// <summary>
        /// Test the property 'Envelopes'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopesTest()
        {
            // TODO unit test for the property 'Envelopes'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'LastUsed'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastUsedTest()
        {
            // TODO unit test for the property 'LastUsed'
        }
        /// <summary>
        /// Test the property 'LimitUseInterval'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LimitUseIntervalTest()
        {
            // TODO unit test for the property 'LimitUseInterval'
        }
        /// <summary>
        /// Test the property 'LimitUseIntervalEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LimitUseIntervalEnabledTest()
        {
            // TODO unit test for the property 'LimitUseIntervalEnabled'
        }
        /// <summary>
        /// Test the property 'LimitUseIntervalUnits'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LimitUseIntervalUnitsTest()
        {
            // TODO unit test for the property 'LimitUseIntervalUnits'
        }
        /// <summary>
        /// Test the property 'MaxUseEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void MaxUseEnabledTest()
        {
            // TODO unit test for the property 'MaxUseEnabled'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PowerFormId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PowerFormIdTest()
        {
            // TODO unit test for the property 'PowerFormId'
        }
        /// <summary>
        /// Test the property 'PowerFormUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PowerFormUrlTest()
        {
            // TODO unit test for the property 'PowerFormUrl'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'SenderUserId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderUserIdTest()
        {
            // TODO unit test for the property 'SenderUserId'
        }
        /// <summary>
        /// Test the property 'SigningMode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SigningModeTest()
        {
            // TODO unit test for the property 'SigningMode'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'TemplateName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateNameTest()
        {
            // TODO unit test for the property 'TemplateName'
        }
        /// <summary>
        /// Test the property 'TimesUsed'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TimesUsedTest()
        {
            // TODO unit test for the property 'TimesUsed'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'UsesRemaining'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UsesRemainingTest()
        {
            // TODO unit test for the property 'UsesRemaining'
        }

    }

}
