/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing PowerFormRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class PowerFormRecipientTests
    {
        // TODO uncomment below to declare an instance variable for PowerFormRecipient
        //private PowerFormRecipient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of PowerFormRecipient
            //instance = new PowerFormRecipient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PowerFormRecipient
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PowerFormRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PowerFormRecipient
            //NUnit.Framework.Assert.IsInstanceOf<PowerFormRecipient> (instance, "variable 'instance' is a PowerFormRecipient");
        }

        /// <summary>
        /// Test the property 'AccessCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccessCodeTest()
        {
            // TODO unit test for the property 'AccessCode'
        }
        /// <summary>
        /// Test the property 'AccessCodeLocked'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccessCodeLockedTest()
        {
            // TODO unit test for the property 'AccessCodeLocked'
        }
        /// <summary>
        /// Test the property 'AccessCodeRequired'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccessCodeRequiredTest()
        {
            // TODO unit test for the property 'AccessCodeRequired'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EmailLocked'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailLockedTest()
        {
            // TODO unit test for the property 'EmailLocked'
        }
        /// <summary>
        /// Test the property 'IdCheckConfigurationName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IdCheckConfigurationNameTest()
        {
            // TODO unit test for the property 'IdCheckConfigurationName'
        }
        /// <summary>
        /// Test the property 'IdCheckRequired'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IdCheckRequiredTest()
        {
            // TODO unit test for the property 'IdCheckRequired'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecipientType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientTypeTest()
        {
            // TODO unit test for the property 'RecipientType'
        }
        /// <summary>
        /// Test the property 'RoleName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RoleNameTest()
        {
            // TODO unit test for the property 'RoleName'
        }
        /// <summary>
        /// Test the property 'RoutingOrder'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RoutingOrderTest()
        {
            // TODO unit test for the property 'RoutingOrder'
        }
        /// <summary>
        /// Test the property 'TemplateRequiresIdLookup'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateRequiresIdLookupTest()
        {
            // TODO unit test for the property 'TemplateRequiresIdLookup'
        }
        /// <summary>
        /// Test the property 'UserNameLocked'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserNameLockedTest()
        {
            // TODO unit test for the property 'UserNameLocked'
        }

    }

}
