/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing PropertyMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class PropertyMetadataTests
    {
        // TODO uncomment below to declare an instance variable for PropertyMetadata
        //private PropertyMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertyMetadata
            //instance = new PropertyMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertyMetadata
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PropertyMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PropertyMetadata
            //NUnit.Framework.Assert.IsInstanceOf<PropertyMetadata> (instance, "variable 'instance' is a PropertyMetadata");
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Rights'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RightsTest()
        {
            // TODO unit test for the property 'Rights'
        }

    }

}
