/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ProvisioningInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ProvisioningInformationTests
    {
        // TODO uncomment below to declare an instance variable for ProvisioningInformation
        //private ProvisioningInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProvisioningInformation
            //instance = new ProvisioningInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProvisioningInformation
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ProvisioningInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProvisioningInformation
            //NUnit.Framework.Assert.IsInstanceOf<ProvisioningInformation> (instance, "variable 'instance' is a ProvisioningInformation");
        }

        /// <summary>
        /// Test the property 'DefaultConnectionId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DefaultConnectionIdTest()
        {
            // TODO unit test for the property 'DefaultConnectionId'
        }
        /// <summary>
        /// Test the property 'DefaultPlanId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DefaultPlanIdTest()
        {
            // TODO unit test for the property 'DefaultPlanId'
        }
        /// <summary>
        /// Test the property 'DistributorCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DistributorCodeTest()
        {
            // TODO unit test for the property 'DistributorCode'
        }
        /// <summary>
        /// Test the property 'DistributorPassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DistributorPasswordTest()
        {
            // TODO unit test for the property 'DistributorPassword'
        }
        /// <summary>
        /// Test the property 'PasswordRuleText'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PasswordRuleTextTest()
        {
            // TODO unit test for the property 'PasswordRuleText'
        }
        /// <summary>
        /// Test the property 'PlanPromotionText'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanPromotionTextTest()
        {
            // TODO unit test for the property 'PlanPromotionText'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderOrPromAllowed'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PurchaseOrderOrPromAllowedTest()
        {
            // TODO unit test for the property 'PurchaseOrderOrPromAllowed'
        }

    }

}
