/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing RecipientPhoneAuthentication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class RecipientPhoneAuthenticationTests
    {
        // TODO uncomment below to declare an instance variable for RecipientPhoneAuthentication
        //private RecipientPhoneAuthentication instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecipientPhoneAuthentication
            //instance = new RecipientPhoneAuthentication();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecipientPhoneAuthentication
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientPhoneAuthenticationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecipientPhoneAuthentication
            //NUnit.Framework.Assert.IsInstanceOf<RecipientPhoneAuthentication> (instance, "variable 'instance' is a RecipientPhoneAuthentication");
        }

        /// <summary>
        /// Test the property 'RecipMayProvideNumber'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipMayProvideNumberTest()
        {
            // TODO unit test for the property 'RecipMayProvideNumber'
        }
        /// <summary>
        /// Test the property 'RecordVoicePrint'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecordVoicePrintTest()
        {
            // TODO unit test for the property 'RecordVoicePrint'
        }
        /// <summary>
        /// Test the property 'SenderProvidedNumbers'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderProvidedNumbersTest()
        {
            // TODO unit test for the property 'SenderProvidedNumbers'
        }
        /// <summary>
        /// Test the property 'ValidateRecipProvidedNumber'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ValidateRecipProvidedNumberTest()
        {
            // TODO unit test for the property 'ValidateRecipProvidedNumber'
        }

    }

}
