/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing RecipientSignatureProviderOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class RecipientSignatureProviderOptionsTests
    {
        // TODO uncomment below to declare an instance variable for RecipientSignatureProviderOptions
        //private RecipientSignatureProviderOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecipientSignatureProviderOptions
            //instance = new RecipientSignatureProviderOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecipientSignatureProviderOptions
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientSignatureProviderOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecipientSignatureProviderOptions
            //NUnit.Framework.Assert.IsInstanceOf<RecipientSignatureProviderOptions> (instance, "variable 'instance' is a RecipientSignatureProviderOptions");
        }

        /// <summary>
        /// Test the property 'CpfNumber'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CpfNumberTest()
        {
            // TODO unit test for the property 'CpfNumber'
        }
        /// <summary>
        /// Test the property 'OneTimePassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OneTimePasswordTest()
        {
            // TODO unit test for the property 'OneTimePassword'
        }
        /// <summary>
        /// Test the property 'SignerRole'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignerRoleTest()
        {
            // TODO unit test for the property 'SignerRole'
        }
        /// <summary>
        /// Test the property 'Sms'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SmsTest()
        {
            // TODO unit test for the property 'Sms'
        }

    }

}
