/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ReferralInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ReferralInformationTests
    {
        // TODO uncomment below to declare an instance variable for ReferralInformation
        //private ReferralInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReferralInformation
            //instance = new ReferralInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReferralInformation
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReferralInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReferralInformation
            //NUnit.Framework.Assert.IsInstanceOf<ReferralInformation> (instance, "variable 'instance' is a ReferralInformation");
        }

        /// <summary>
        /// Test the property 'AdvertisementId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AdvertisementIdTest()
        {
            // TODO unit test for the property 'AdvertisementId'
        }
        /// <summary>
        /// Test the property 'EnableSupport'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnableSupportTest()
        {
            // TODO unit test for the property 'EnableSupport'
        }
        /// <summary>
        /// Test the property 'ExternalOrgId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExternalOrgIdTest()
        {
            // TODO unit test for the property 'ExternalOrgId'
        }
        /// <summary>
        /// Test the property 'GroupMemberId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void GroupMemberIdTest()
        {
            // TODO unit test for the property 'GroupMemberId'
        }
        /// <summary>
        /// Test the property 'IdType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IdTypeTest()
        {
            // TODO unit test for the property 'IdType'
        }
        /// <summary>
        /// Test the property 'IncludedSeats'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IncludedSeatsTest()
        {
            // TODO unit test for the property 'IncludedSeats'
        }
        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }
        /// <summary>
        /// Test the property 'PlanStartMonth'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PlanStartMonthTest()
        {
            // TODO unit test for the property 'PlanStartMonth'
        }
        /// <summary>
        /// Test the property 'PromoCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PromoCodeTest()
        {
            // TODO unit test for the property 'PromoCode'
        }
        /// <summary>
        /// Test the property 'PublisherId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PublisherIdTest()
        {
            // TODO unit test for the property 'PublisherId'
        }
        /// <summary>
        /// Test the property 'ReferralCode'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReferralCodeTest()
        {
            // TODO unit test for the property 'ReferralCode'
        }
        /// <summary>
        /// Test the property 'ReferrerName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReferrerNameTest()
        {
            // TODO unit test for the property 'ReferrerName'
        }
        /// <summary>
        /// Test the property 'SaleDiscountAmount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SaleDiscountAmountTest()
        {
            // TODO unit test for the property 'SaleDiscountAmount'
        }
        /// <summary>
        /// Test the property 'SaleDiscountFixedAmount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SaleDiscountFixedAmountTest()
        {
            // TODO unit test for the property 'SaleDiscountFixedAmount'
        }
        /// <summary>
        /// Test the property 'SaleDiscountPercent'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SaleDiscountPercentTest()
        {
            // TODO unit test for the property 'SaleDiscountPercent'
        }
        /// <summary>
        /// Test the property 'SaleDiscountPeriods'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SaleDiscountPeriodsTest()
        {
            // TODO unit test for the property 'SaleDiscountPeriods'
        }
        /// <summary>
        /// Test the property 'SaleDiscountSeatPriceOverride'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SaleDiscountSeatPriceOverrideTest()
        {
            // TODO unit test for the property 'SaleDiscountSeatPriceOverride'
        }
        /// <summary>
        /// Test the property 'ShopperId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ShopperIdTest()
        {
            // TODO unit test for the property 'ShopperId'
        }

    }

}
