/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Reminders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class RemindersTests
    {
        // TODO uncomment below to declare an instance variable for Reminders
        //private Reminders instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Reminders
            //instance = new Reminders();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Reminders
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RemindersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Reminders
            //NUnit.Framework.Assert.IsInstanceOf<Reminders> (instance, "variable 'instance' is a Reminders");
        }

        /// <summary>
        /// Test the property 'ReminderDelay'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReminderDelayTest()
        {
            // TODO unit test for the property 'ReminderDelay'
        }
        /// <summary>
        /// Test the property 'ReminderEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReminderEnabledTest()
        {
            // TODO unit test for the property 'ReminderEnabled'
        }
        /// <summary>
        /// Test the property 'ReminderFrequency'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReminderFrequencyTest()
        {
            // TODO unit test for the property 'ReminderFrequency'
        }

    }

}
