/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Seal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class SealTests
    {
        // TODO uncomment below to declare an instance variable for Seal
        //private Seal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Seal
            //instance = new Seal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Seal
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SealInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Seal
            //NUnit.Framework.Assert.IsInstanceOf<Seal> (instance, "variable 'instance' is a Seal");
        }

        /// <summary>
        /// Test the property 'Configuration'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ConfigurationTest()
        {
            // TODO unit test for the property 'Configuration'
        }
        /// <summary>
        /// Test the property 'SealIdentifier'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SealIdentifierTest()
        {
            // TODO unit test for the property 'SealIdentifier'
        }

    }

}
