/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing SenderEmailNotifications
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class SenderEmailNotificationsTests
    {
        // TODO uncomment below to declare an instance variable for SenderEmailNotifications
        //private SenderEmailNotifications instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of SenderEmailNotifications
            //instance = new SenderEmailNotifications();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SenderEmailNotifications
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderEmailNotificationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SenderEmailNotifications
            //NUnit.Framework.Assert.IsInstanceOf<SenderEmailNotifications> (instance, "variable 'instance' is a SenderEmailNotifications");
        }

        /// <summary>
        /// Test the property 'ChangedSigner'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ChangedSignerTest()
        {
            // TODO unit test for the property 'ChangedSigner'
        }
        /// <summary>
        /// Test the property 'DeliveryFailed'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DeliveryFailedTest()
        {
            // TODO unit test for the property 'DeliveryFailed'
        }
        /// <summary>
        /// Test the property 'EnvelopeComplete'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeCompleteTest()
        {
            // TODO unit test for the property 'EnvelopeComplete'
        }
        /// <summary>
        /// Test the property 'OfflineSigningFailed'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void OfflineSigningFailedTest()
        {
            // TODO unit test for the property 'OfflineSigningFailed'
        }
        /// <summary>
        /// Test the property 'RecipientViewed'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientViewedTest()
        {
            // TODO unit test for the property 'RecipientViewed'
        }
        /// <summary>
        /// Test the property 'SenderEnvelopeDeclined'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderEnvelopeDeclinedTest()
        {
            // TODO unit test for the property 'SenderEnvelopeDeclined'
        }
        /// <summary>
        /// Test the property 'WithdrawnConsent'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WithdrawnConsentTest()
        {
            // TODO unit test for the property 'WithdrawnConsent'
        }

    }

}
