/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ServerTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ServerTemplateTests
    {
        // TODO uncomment below to declare an instance variable for ServerTemplate
        //private ServerTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServerTemplate
            //instance = new ServerTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServerTemplate
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ServerTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServerTemplate
            //NUnit.Framework.Assert.IsInstanceOf<ServerTemplate> (instance, "variable 'instance' is a ServerTemplate");
        }

        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

    }

}
