/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing SignHashDocument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class SignHashDocumentTests
    {
        // TODO uncomment below to declare an instance variable for SignHashDocument
        //private SignHashDocument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignHashDocument
            //instance = new SignHashDocument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignHashDocument
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignHashDocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignHashDocument
            //NUnit.Framework.Assert.IsInstanceOf<SignHashDocument> (instance, "variable 'instance' is a SignHashDocument");
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RemainingSignatures'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RemainingSignaturesTest()
        {
            // TODO unit test for the property 'RemainingSignatures'
        }
        /// <summary>
        /// Test the property 'Revisions'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RevisionsTest()
        {
            // TODO unit test for the property 'Revisions'
        }
        /// <summary>
        /// Test the property 'SignatureType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignatureTypeTest()
        {
            // TODO unit test for the property 'SignatureType'
        }

    }

}
