/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing SignHashSessionInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class SignHashSessionInfoResponseTests
    {
        // TODO uncomment below to declare an instance variable for SignHashSessionInfoResponse
        //private SignHashSessionInfoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignHashSessionInfoResponse
            //instance = new SignHashSessionInfoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignHashSessionInfoResponse
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignHashSessionInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignHashSessionInfoResponse
            //NUnit.Framework.Assert.IsInstanceOf<SignHashSessionInfoResponse> (instance, "variable 'instance' is a SignHashSessionInfoResponse");
        }

        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'RedirectionUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RedirectionUrlTest()
        {
            // TODO unit test for the property 'RedirectionUrl'
        }
        /// <summary>
        /// Test the property 'RemainingSignatureRequests'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RemainingSignatureRequestsTest()
        {
            // TODO unit test for the property 'RemainingSignatureRequests'
        }
        /// <summary>
        /// Test the property 'Seal'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SealTest()
        {
            // TODO unit test for the property 'Seal'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
