/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing SocialAuthentication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class SocialAuthenticationTests
    {
        // TODO uncomment below to declare an instance variable for SocialAuthentication
        //private SocialAuthentication instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of SocialAuthentication
            //instance = new SocialAuthentication();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SocialAuthentication
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SocialAuthenticationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SocialAuthentication
            //NUnit.Framework.Assert.IsInstanceOf<SocialAuthentication> (instance, "variable 'instance' is a SocialAuthentication");
        }

        /// <summary>
        /// Test the property 'Authentication'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AuthenticationTest()
        {
            // TODO unit test for the property 'Authentication'
        }

    }

}
