/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing TabAccountSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class TabAccountSettingsTests
    {
        // TODO uncomment below to declare an instance variable for TabAccountSettings
        //private TabAccountSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of TabAccountSettings
            //instance = new TabAccountSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TabAccountSettings
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabAccountSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TabAccountSettings
            //NUnit.Framework.Assert.IsInstanceOf<TabAccountSettings> (instance, "variable 'instance' is a TabAccountSettings");
        }

        /// <summary>
        /// Test the property 'AllowTabOrder'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowTabOrderTest()
        {
            // TODO unit test for the property 'AllowTabOrder'
        }
        /// <summary>
        /// Test the property 'AllowTabOrderMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AllowTabOrderMetadataTest()
        {
            // TODO unit test for the property 'AllowTabOrderMetadata'
        }
        /// <summary>
        /// Test the property 'ApproveDeclineTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ApproveDeclineTabsEnabledTest()
        {
            // TODO unit test for the property 'ApproveDeclineTabsEnabled'
        }
        /// <summary>
        /// Test the property 'ApproveDeclineTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ApproveDeclineTabsMetadataTest()
        {
            // TODO unit test for the property 'ApproveDeclineTabsMetadata'
        }
        /// <summary>
        /// Test the property 'CalculatedFieldsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CalculatedFieldsEnabledTest()
        {
            // TODO unit test for the property 'CalculatedFieldsEnabled'
        }
        /// <summary>
        /// Test the property 'CalculatedFieldsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CalculatedFieldsMetadataTest()
        {
            // TODO unit test for the property 'CalculatedFieldsMetadata'
        }
        /// <summary>
        /// Test the property 'CheckboxTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CheckboxTabsEnabledTest()
        {
            // TODO unit test for the property 'CheckboxTabsEnabled'
        }
        /// <summary>
        /// Test the property 'CheckboxTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CheckboxTabsMetadataTest()
        {
            // TODO unit test for the property 'CheckboxTabsMetadata'
        }
        /// <summary>
        /// Test the property 'DataFieldRegexEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataFieldRegexEnabledTest()
        {
            // TODO unit test for the property 'DataFieldRegexEnabled'
        }
        /// <summary>
        /// Test the property 'DataFieldRegexMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataFieldRegexMetadataTest()
        {
            // TODO unit test for the property 'DataFieldRegexMetadata'
        }
        /// <summary>
        /// Test the property 'DataFieldSizeEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataFieldSizeEnabledTest()
        {
            // TODO unit test for the property 'DataFieldSizeEnabled'
        }
        /// <summary>
        /// Test the property 'DataFieldSizeMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DataFieldSizeMetadataTest()
        {
            // TODO unit test for the property 'DataFieldSizeMetadata'
        }
        /// <summary>
        /// Test the property 'FirstLastEmailTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FirstLastEmailTabsEnabledTest()
        {
            // TODO unit test for the property 'FirstLastEmailTabsEnabled'
        }
        /// <summary>
        /// Test the property 'FirstLastEmailTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FirstLastEmailTabsMetadataTest()
        {
            // TODO unit test for the property 'FirstLastEmailTabsMetadata'
        }
        /// <summary>
        /// Test the property 'ListTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ListTabsEnabledTest()
        {
            // TODO unit test for the property 'ListTabsEnabled'
        }
        /// <summary>
        /// Test the property 'ListTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ListTabsMetadataTest()
        {
            // TODO unit test for the property 'ListTabsMetadata'
        }
        /// <summary>
        /// Test the property 'NoteTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NoteTabsEnabledTest()
        {
            // TODO unit test for the property 'NoteTabsEnabled'
        }
        /// <summary>
        /// Test the property 'NoteTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NoteTabsMetadataTest()
        {
            // TODO unit test for the property 'NoteTabsMetadata'
        }
        /// <summary>
        /// Test the property 'RadioTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RadioTabsEnabledTest()
        {
            // TODO unit test for the property 'RadioTabsEnabled'
        }
        /// <summary>
        /// Test the property 'RadioTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RadioTabsMetadataTest()
        {
            // TODO unit test for the property 'RadioTabsMetadata'
        }
        /// <summary>
        /// Test the property 'SavingCustomTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SavingCustomTabsEnabledTest()
        {
            // TODO unit test for the property 'SavingCustomTabsEnabled'
        }
        /// <summary>
        /// Test the property 'SavingCustomTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SavingCustomTabsMetadataTest()
        {
            // TODO unit test for the property 'SavingCustomTabsMetadata'
        }
        /// <summary>
        /// Test the property 'SenderToChangeTabAssignmentsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderToChangeTabAssignmentsEnabledTest()
        {
            // TODO unit test for the property 'SenderToChangeTabAssignmentsEnabled'
        }
        /// <summary>
        /// Test the property 'SenderToChangeTabAssignmentsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SenderToChangeTabAssignmentsMetadataTest()
        {
            // TODO unit test for the property 'SenderToChangeTabAssignmentsMetadata'
        }
        /// <summary>
        /// Test the property 'SharedCustomTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SharedCustomTabsEnabledTest()
        {
            // TODO unit test for the property 'SharedCustomTabsEnabled'
        }
        /// <summary>
        /// Test the property 'SharedCustomTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SharedCustomTabsMetadataTest()
        {
            // TODO unit test for the property 'SharedCustomTabsMetadata'
        }
        /// <summary>
        /// Test the property 'TabDataLabelEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabDataLabelEnabledTest()
        {
            // TODO unit test for the property 'TabDataLabelEnabled'
        }
        /// <summary>
        /// Test the property 'TabDataLabelMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabDataLabelMetadataTest()
        {
            // TODO unit test for the property 'TabDataLabelMetadata'
        }
        /// <summary>
        /// Test the property 'TabLocationEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabLocationEnabledTest()
        {
            // TODO unit test for the property 'TabLocationEnabled'
        }
        /// <summary>
        /// Test the property 'TabLocationMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabLocationMetadataTest()
        {
            // TODO unit test for the property 'TabLocationMetadata'
        }
        /// <summary>
        /// Test the property 'TabLockingEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabLockingEnabledTest()
        {
            // TODO unit test for the property 'TabLockingEnabled'
        }
        /// <summary>
        /// Test the property 'TabLockingMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabLockingMetadataTest()
        {
            // TODO unit test for the property 'TabLockingMetadata'
        }
        /// <summary>
        /// Test the property 'TabScaleEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabScaleEnabledTest()
        {
            // TODO unit test for the property 'TabScaleEnabled'
        }
        /// <summary>
        /// Test the property 'TabScaleMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabScaleMetadataTest()
        {
            // TODO unit test for the property 'TabScaleMetadata'
        }
        /// <summary>
        /// Test the property 'TabTextFormattingEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabTextFormattingEnabledTest()
        {
            // TODO unit test for the property 'TabTextFormattingEnabled'
        }
        /// <summary>
        /// Test the property 'TabTextFormattingMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TabTextFormattingMetadataTest()
        {
            // TODO unit test for the property 'TabTextFormattingMetadata'
        }
        /// <summary>
        /// Test the property 'TextTabsEnabled'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TextTabsEnabledTest()
        {
            // TODO unit test for the property 'TextTabsEnabled'
        }
        /// <summary>
        /// Test the property 'TextTabsMetadata'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TextTabsMetadataTest()
        {
            // TODO unit test for the property 'TextTabsMetadata'
        }

    }

}
