/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing TemplateMatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class TemplateMatchTests
    {
        // TODO uncomment below to declare an instance variable for TemplateMatch
        //private TemplateMatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplateMatch
            //instance = new TemplateMatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateMatch
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateMatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplateMatch
            //NUnit.Framework.Assert.IsInstanceOf<TemplateMatch> (instance, "variable 'instance' is a TemplateMatch");
        }

        /// <summary>
        /// Test the property 'DocumentEndPage'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentEndPageTest()
        {
            // TODO unit test for the property 'DocumentEndPage'
        }
        /// <summary>
        /// Test the property 'DocumentStartPage'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void DocumentStartPageTest()
        {
            // TODO unit test for the property 'DocumentStartPage'
        }
        /// <summary>
        /// Test the property 'MatchPercentage'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void MatchPercentageTest()
        {
            // TODO unit test for the property 'MatchPercentage'
        }

    }

}
