/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing TemplateRecipients
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class TemplateRecipientsTests
    {
        // TODO uncomment below to declare an instance variable for TemplateRecipients
        //private TemplateRecipients instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplateRecipients
            //instance = new TemplateRecipients();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateRecipients
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TemplateRecipientsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplateRecipients
            //NUnit.Framework.Assert.IsInstanceOf<TemplateRecipients> (instance, "variable 'instance' is a TemplateRecipients");
        }

        /// <summary>
        /// Test the property 'Agents'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AgentsTest()
        {
            // TODO unit test for the property 'Agents'
        }
        /// <summary>
        /// Test the property 'CarbonCopies'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CarbonCopiesTest()
        {
            // TODO unit test for the property 'CarbonCopies'
        }
        /// <summary>
        /// Test the property 'CertifiedDeliveries'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CertifiedDeliveriesTest()
        {
            // TODO unit test for the property 'CertifiedDeliveries'
        }
        /// <summary>
        /// Test the property 'CurrentRoutingOrder'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CurrentRoutingOrderTest()
        {
            // TODO unit test for the property 'CurrentRoutingOrder'
        }
        /// <summary>
        /// Test the property 'Editors'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EditorsTest()
        {
            // TODO unit test for the property 'Editors'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'InPersonSigners'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void InPersonSignersTest()
        {
            // TODO unit test for the property 'InPersonSigners'
        }
        /// <summary>
        /// Test the property 'Intermediaries'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IntermediariesTest()
        {
            // TODO unit test for the property 'Intermediaries'
        }
        /// <summary>
        /// Test the property 'RecipientCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void RecipientCountTest()
        {
            // TODO unit test for the property 'RecipientCount'
        }
        /// <summary>
        /// Test the property 'Signers'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignersTest()
        {
            // TODO unit test for the property 'Signers'
        }

    }

}
