/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing UsageHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class UsageHistoryTests
    {
        // TODO uncomment below to declare an instance variable for UsageHistory
        //private UsageHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of UsageHistory
            //instance = new UsageHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsageHistory
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UsageHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UsageHistory
            //NUnit.Framework.Assert.IsInstanceOf<UsageHistory> (instance, "variable 'instance' is a UsageHistory");
        }

        /// <summary>
        /// Test the property 'LastSentDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastSentDateTimeTest()
        {
            // TODO unit test for the property 'LastSentDateTime'
        }
        /// <summary>
        /// Test the property 'LastSignedDateTime'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastSignedDateTimeTest()
        {
            // TODO unit test for the property 'LastSignedDateTime'
        }
        /// <summary>
        /// Test the property 'SentCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SentCountTest()
        {
            // TODO unit test for the property 'SentCount'
        }
        /// <summary>
        /// Test the property 'SignedCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void SignedCountTest()
        {
            // TODO unit test for the property 'SignedCount'
        }

    }

}
