/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing UsersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class UsersResponseTests
    {
        // TODO uncomment below to declare an instance variable for UsersResponse
        //private UsersResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of UsersResponse
            //instance = new UsersResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersResponse
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UsersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UsersResponse
            //NUnit.Framework.Assert.IsInstanceOf<UsersResponse> (instance, "variable 'instance' is a UsersResponse");
        }

        /// <summary>
        /// Test the property 'EndPosition'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EndPositionTest()
        {
            // TODO unit test for the property 'EndPosition'
        }
        /// <summary>
        /// Test the property 'NextUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NextUriTest()
        {
            // TODO unit test for the property 'NextUri'
        }
        /// <summary>
        /// Test the property 'PreviousUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PreviousUriTest()
        {
            // TODO unit test for the property 'PreviousUri'
        }
        /// <summary>
        /// Test the property 'ResultSetSize'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ResultSetSizeTest()
        {
            // TODO unit test for the property 'ResultSetSize'
        }
        /// <summary>
        /// Test the property 'StartPosition'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StartPositionTest()
        {
            // TODO unit test for the property 'StartPosition'
        }
        /// <summary>
        /// Test the property 'TotalSetSize'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TotalSetSizeTest()
        {
            // TODO unit test for the property 'TotalSetSize'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
