/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing UserPasswordInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class UserPasswordInformationTests
    {
        // TODO uncomment below to declare an instance variable for UserPasswordInformation
        //private UserPasswordInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserPasswordInformation
            //instance = new UserPasswordInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserPasswordInformation
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserPasswordInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserPasswordInformation
            //NUnit.Framework.Assert.IsInstanceOf<UserPasswordInformation> (instance, "variable 'instance' is a UserPasswordInformation");
        }

        /// <summary>
        /// Test the property 'CurrentPassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CurrentPasswordTest()
        {
            // TODO unit test for the property 'CurrentPassword'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ForgottenPasswordInfo'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ForgottenPasswordInfoTest()
        {
            // TODO unit test for the property 'ForgottenPasswordInfo'
        }
        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

    }

}
