/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing ViewLinkRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class ViewLinkRequestTests
    {
        // TODO uncomment below to declare an instance variable for ViewLinkRequest
        //private ViewLinkRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of ViewLinkRequest
            //instance = new ViewLinkRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ViewLinkRequest
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ViewLinkRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ViewLinkRequest
            //NUnit.Framework.Assert.IsInstanceOf<ViewLinkRequest> (instance, "variable 'instance' is a ViewLinkRequest");
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

    }

}
