/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing Workspace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class WorkspaceTests
    {
        // TODO uncomment below to declare an instance variable for Workspace
        //private Workspace instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of Workspace
            //instance = new Workspace();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Workspace
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Workspace
            //NUnit.Framework.Assert.IsInstanceOf<Workspace> (instance, "variable 'instance' is a Workspace");
        }

        /// <summary>
        /// Test the property 'BillableAccountId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void BillableAccountIdTest()
        {
            // TODO unit test for the property 'BillableAccountId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CreatedByInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedByInformationTest()
        {
            // TODO unit test for the property 'CreatedByInformation'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'LastModifiedByInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedByInformationTest()
        {
            // TODO unit test for the property 'LastModifiedByInformation'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'WorkspaceBaseUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceBaseUrlTest()
        {
            // TODO unit test for the property 'WorkspaceBaseUrl'
        }
        /// <summary>
        /// Test the property 'WorkspaceDescription'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceDescriptionTest()
        {
            // TODO unit test for the property 'WorkspaceDescription'
        }
        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }
        /// <summary>
        /// Test the property 'WorkspaceName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceNameTest()
        {
            // TODO unit test for the property 'WorkspaceName'
        }
        /// <summary>
        /// Test the property 'WorkspaceUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceUriTest()
        {
            // TODO unit test for the property 'WorkspaceUri'
        }

    }

}
