/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing WorkspaceItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class WorkspaceItemTests
    {
        // TODO uncomment below to declare an instance variable for WorkspaceItem
        //private WorkspaceItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkspaceItem
            //instance = new WorkspaceItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkspaceItem
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkspaceItem
            //NUnit.Framework.Assert.IsInstanceOf<WorkspaceItem> (instance, "variable 'instance' is a WorkspaceItem");
        }

        /// <summary>
        /// Test the property 'CallerAuthorization'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CallerAuthorizationTest()
        {
            // TODO unit test for the property 'CallerAuthorization'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CreatedById'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedByIdTest()
        {
            // TODO unit test for the property 'CreatedById'
        }
        /// <summary>
        /// Test the property 'CreatedByInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedByInformationTest()
        {
            // TODO unit test for the property 'CreatedByInformation'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'FileUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void FileUriTest()
        {
            // TODO unit test for the property 'FileUri'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'LastModifiedById'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedByIdTest()
        {
            // TODO unit test for the property 'LastModifiedById'
        }
        /// <summary>
        /// Test the property 'LastModifiedByInformation'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedByInformationTest()
        {
            // TODO unit test for the property 'LastModifiedByInformation'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'ParentFolderId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ParentFolderIdTest()
        {
            // TODO unit test for the property 'ParentFolderId'
        }
        /// <summary>
        /// Test the property 'ParentFolderUri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ParentFolderUriTest()
        {
            // TODO unit test for the property 'ParentFolderUri'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
