/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing WorkspaceUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [NUnit.Framework.TestFixtureAttribute]
    public class WorkspaceUserTests
    {
        // TODO uncomment below to declare an instance variable for WorkspaceUser
        //private WorkspaceUser instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [NUnit.Framework.SetUpAttribute]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkspaceUser
            //instance = new WorkspaceUser();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkspaceUser
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkspaceUser
            //NUnit.Framework.Assert.IsInstanceOf<WorkspaceUser> (instance, "variable 'instance' is a WorkspaceUser");
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'ActiveSince'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ActiveSinceTest()
        {
            // TODO unit test for the property 'ActiveSince'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CreatedById'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void CreatedByIdTest()
        {
            // TODO unit test for the property 'CreatedById'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'LastModifiedById'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void LastModifiedByIdTest()
        {
            // TODO unit test for the property 'LastModifiedById'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }
        /// <summary>
        /// Test the property 'WorkspaceUserBaseUrl'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceUserBaseUrlTest()
        {
            // TODO unit test for the property 'WorkspaceUserBaseUrl'
        }
        /// <summary>
        /// Test the property 'WorkspaceUserId'
        /// </summary>
        [NUnit.Framework.TestAttribute]
        public void WorkspaceUserIdTest()
        {
            // TODO unit test for the property 'WorkspaceUserId'
        }

    }

}
